### ISSUE TITLE
Devices need to be shown as away when not connected to WiFi

### ISSUE THREAD

**Issue by smccloud** [agrieco/merakicmx#3]
I switched from the UniFi tracker to the Meraki tracker when I switched from Ubiquiti to Meraki and your code works but it does not say when a device has disconnected from the WiFi.  Due to this, I have automations firing when they shouldn't.  Please update your code to show devices as away when they aren't on the WiFI.

**Comment by agrieco** [comment]
Please use the officially supported Meraki component inside Home Assistant

https://www.home-assistant.io/components/device_tracker.meraki/

I'll deprecate this code and update the readme.
